name: Yarn upgrade

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  schedule:
  - cron: "0 10 * 1-12 6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    # Read node version from `.nvmrc` file
    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1

    - uses: actions/setup-node@v1
      with:
        # use the output from the action
        node-version: '${{ steps.nvmrc.outputs.node_version }}'

    # Run `yarn upgrade`
    - uses: browniebroke/yarn-upgrade-action@v1

    # Open a pull request if there are any changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/yarn-upgrade
        title: Dependencies upgrade
        commit-message: "chore(deps): Dependencies upgrade :arrow_up:"
